extends: default
ignore: |
  .tox
  src/data/sova-patterns.yml

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  document-start: disable
  line-length: disable
  truthy:
    check-keys: false
