name: gh

on:
  create:  # is used for publishing to PyPI and TestPyPI
    tags:  # any tag regardless of its name, no branches
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any integration branch but not tag
      - "master"
      - "main"
    tags-ignore:
      - >-
        **
  pull_request:
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

jobs:
  linters:
    name: >-
      ${{ matrix.env.TOXENV }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
        os:
          - ubuntu-20.04
        env:
          - TOXENV: lint
          - TOXENV: py38
    env:
      TOX_PARALLEL_NO_SPINNER: 1
      FORCE_COLOR: 1

    steps:
      - name: Check out src from Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # needed by setuptools-scm
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          python3 -m pip install --upgrade 'tox>=4.0.0a4'
      - name: Log installed dists
        run: >-
          python -m pip freeze --all
      - name: Test with tox
        run: |
          python -m tox
        env: ${{ matrix.env }}
